//
//  AdLimeNetwork.h
//  Created by AdLimeSdk on 2019/6/15.
//

#import <Foundation/Foundation.h>

/*!
Id of Network supported by SDK.
 */
typedef NS_ENUM(NSInteger, AdLimeNetworkId) {
    ADLIME_NETWORK_UNKNOWN = 0,
    ADLIME_NETWORK_ADCOLONY = 1,
    ADLIME_NETWORK_ADMOB = 2,
    ADLIME_NETWORK_APPLOVIN = 3,
    ADLIME_NETWORK_CHARTBOOST = 4,
    ADLIME_NETWORK_FACEBOOK = 5,
    ADLIME_NETWORK_IRON_SOURCE = 6,
    ADLIME_NETWORK_MOPUB = 7,
    ADLIME_NETWORK_UNITY = 8,
    ADLIME_NETWORK_MARKETPLACE = 9,
    ADLIME_NETWORK_FYBER = 10,
    ADLIME_NETWORK_INMOBI = 11,
    ADLIME_NETWORK_VUNGLE = 12,
    ADLIME_NETWORK_GOOGLE_AD_MANAGER = 13,
    ADLIME_NETWORK_CREATIVE = 14,
    ADLIME_NETWORK_DAP = 15,
    ADLIME_NETWORK_BAIDU = 16,
    ADLIME_NETWORK_DISPLAYIO = 17,
    ADLIME_NETWORK_TOUTIAO = 18,
    ADLIME_NETWORK_GDT = 19,
    ADLIME_NETWORK_AMAZON = 20,
    ADLIME_NETWORK_FLURRY = 21,
    ADLIME_NETWORK_TAPJOY = 22,
    ADLIME_NETWORK_360 = 23,
    ADLIME_NETWORK_XIAOMI = 24,
    ADLIME_NETWORK_4399 = 25,
    ADLIME_NETWORK_OPPO = 26,
    ADLIME_NETWORK_VIVO = 27,
    ADLIME_NETWORK_MOBVISTA = 28,
    ADLIME_NETWORK_NEND = 29,
    ADLIME_NETWORK_ADGENERATION = 30,
    ADLIME_NETWORK_MAIO = 31,
    ADLIME_NETWORK_ALIGAMES = 32,
    ADLIME_NETWORK_CRITEO = 33,
    ADLIME_NETWORK_ZHONGHUI_ADS = 34,
    ADLIME_NETWORK_TMS = 35,
    ADLIME_NETWORK_FIVE = 36,
    ADLIME_NETWORK_KUAISHOU = 37,
    ADLIME_NETWORK_IMOBILE = 38,
    ADLIME_NETWORK_PANGLE = 39,
    ADLIME_NETWORK_SIGMOB = 40,
};

/*!
 Network supported by SDK.
 */
@interface AdLimeNetwork : NSObject

/*!
 @brief Id of Network.
 @see AdLimeNetworkId
 */
@property AdLimeNetworkId mid;

/*!
 @brief Name of Network.
 */
@property NSString *name;

+(AdLimeNetwork *)fromId:(int)networkId;
+(NSString *)getName:(AdLimeNetworkId)networkId;

@end
